import { Router } from 'express';
import aegisRouter from './aegis';
import apexRouter from './apex';
import ascendantRouter from './ascendant';
import chronosRouter from './chronos';
import continuumRouter from './continuum';
import echelonRouter from './echelon';
import eternumRouter from './eternum';
import fusionRouter from './fusion';
import genesisRouter from './genesis';
import heliosRouter from './helios';
import helixRouter from './helix';
import hyperionRouter from './hyperion';
import infinityRouter from './infinity';
import lumenRouter from './lumen';
import monarchRouter from './monarch';
import nexusRouter from './nexus';
import nexus2Router from './nexus2';
import omegaRouter from './omega';
import oracleRouter from './oracle';
import overmindRouter from './overmind';
import overwatchRouter from './overwatch';
import pantheonRouter from './pantheon';
import paragonRouter from './paragon';
import primeRouter from './prime';
import sentinelRouter from './sentinel';
import solarisRouter from './solaris';
import sovereignRouter from './sovereign';

const router = Router();

router.use('/aegis', aegisRouter);
router.use('/apex', apexRouter);
router.use('/ascendant', ascendantRouter);
router.use('/chronos', chronosRouter);
router.use('/continuum', continuumRouter);
router.use('/echelon', echelonRouter);
router.use('/eternum', eternumRouter);
router.use('/fusion', fusionRouter);
router.use('/genesis', genesisRouter);
router.use('/helios', heliosRouter);
router.use('/helix', helixRouter);
router.use('/hyperion', hyperionRouter);
router.use('/infinity', infinityRouter);
router.use('/lumen', lumenRouter);
router.use('/monarch', monarchRouter);
router.use('/nexus', nexusRouter);
router.use('/nexus2', nexus2Router);
router.use('/omega', omegaRouter);
router.use('/oracle', oracleRouter);
router.use('/overmind', overmindRouter);
router.use('/overwatch', overwatchRouter);
router.use('/pantheon', pantheonRouter);
router.use('/paragon', paragonRouter);
router.use('/prime', primeRouter);
router.use('/sentinel', sentinelRouter);
router.use('/solaris', solarisRouter);
router.use('/sovereign', sovereignRouter);

export default router;
