name: CD Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Images
        run: docker-compose -f docker-compose.production.yml build
      - name: Run Migrations
        run: ./scripts/migrate.sh
      - name: Deploy
        run: ./scripts/server-init.sh
      - name: Smoke Test
        run: ./scripts/healthcheck.sh
