apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident-frontend
  labels:
    app: trident-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trident-frontend
  template:
    metadata:
      labels:
        app: trident-frontend
    spec:
      containers:
        - name: frontend
          image: trident-frontend:latest
          ports:
            - containerPort: 80
